name: zam_bmi_calculator
description: BMI Calculator App
version: 0.0.1
homepage: https://zamstation.com
publish_to: "none"

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  zam_block_architecture: ^0.1.0
  zam_core: ^0.5.0
  zam_event_bus: ^0.7.0
  zam_event_bus_provider: ^0.3.0
  zam_rules: ^0.1.0
  zam_view_models: ^0.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  zam_test: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/human_body.png

flutter_icons:
  image_path: assets/launcher_icon.png
  android: true
  ios: true
