name: Build

on: [push]

jobs:
  test_docker:
    runs-on: ubuntu-latest
    name: Test Docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/dockeraction
        with:
          who-to-greet: 'Zamstation'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
