name: Build

on: [push]

jobs:
  test_docker:
    name: Test Docker
    runs-on: ubuntu-latest
    container:
      image: zamstation/flutter
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: flutter doctor
        run: flutter doctor
